# Generated by Django 3.1.11 on 2021-06-12 07:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('streak_type', models.CharField(choices=[('Definite', 'Definite'), ('Indefinite', 'Indefinite')], max_length=50, verbose_name='Type of Streak')),
                ('name', models.CharField(max_length=100, verbose_name='Streak Name')),
                ('max_duration', models.PositiveIntegerField(default=1, verbose_name='Maximum Duration in days')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreakRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='User started from')),
                ('punch_in', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_participant', to=settings.AUTH_USER_MODEL)),
                ('streak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='streaks.streak')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
