# Generated by Django 3.1.11 on 2021-06-12 11:44

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text="The length of this field can't be longer than 100", max_length=100, validators=[django.core.validators.RegexValidator(message='Only ASCII characters allowed', regex='^[\\x00-\\x7F]*$')], verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('mobile', models.CharField(help_text='Enter a valid 10 digit mobile number.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Mobile Number', regex='^[1-9]\\d{9}$')], verbose_name='mobile number')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('country_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Invalid Country Code', regex='^\\+[0-9]{1,4}')], verbose_name='Country Code')),
            ],
            options={
                'unique_together': {('country_code', 'mobile')},
            },
        ),
    ]
