# Generated by Django 3.1.11 on 2021-06-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mobile',
            unique_together=None,
        ),
    ]
