# Generated by Django 3.1.11 on 2021-06-14 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210614_2209'),
        ('core', '0002_auto_20210614_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobile',
        ),
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='', max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Country Code', regex='^\\+[0-9]{1,4}')], verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, help_text="The length of this field can't be longer than 100", max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Only ASCII characters allowed', regex='^[\\x00-\\x7F]*$')], verbose_name='name'),
        ),
    ]
