# Generated by Django 3.1.11 on 2021-06-14 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210614_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Country Code', regex='^\\+[0-9]{1,4}')], verbose_name='Country Code'),
        ),
    ]
