# Generated by Django 3.1.11 on 2021-10-20 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211020_2326'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
