# Generated by Django 3.1.11 on 2021-06-15 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streak_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streak_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
