# Generated by Django 3.1.11 on 2021-06-15 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streak_app', '0002_auto_20210615_2122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='streakrecord',
            unique_together={('streak', 'participant')},
        ),
    ]
