# Generated by Django 3.1.11 on 2021-06-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak_app', '0004_auto_20210617_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='streak_type',
            field=models.CharField(choices=[(0, 'Definite'), (1, 'Indefinite')], default=0, max_length=50, verbose_name='Type of Streak'),
        ),
    ]
