# Generated by Django 3.1.11 on 2021-06-20 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak_app', '0007_auto_20210618_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streak',
            old_name='streak_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='streakrecord',
            name='start_date',
        ),
        migrations.AddField(
            model_name='streak',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 18, 39, 53, 95765), verbose_name='Streak Starting from'),
        ),
        migrations.AddField(
            model_name='streakrecord',
            name='started_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 18, 39, 53, 96403), verbose_name='User started from'),
        ),
    ]
