# Generated by Django 3.1.11 on 2021-06-20 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak_app', '0008_auto_20210620_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='streakrecord',
            name='started_from',
        ),
        migrations.AddField(
            model_name='streak',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 18, 42, 27, 788910), verbose_name='Starting From'),
        ),
        migrations.AddField(
            model_name='streakrecord',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 18, 42, 27, 789542), verbose_name='Starting From'),
        ),
    ]
