# Generated by Django 3.1.11 on 2021-06-20 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak_app', '0009_auto_20210620_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='started',
        ),
        migrations.RemoveField(
            model_name='streakrecord',
            name='started',
        ),
        migrations.AddField(
            model_name='streak',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 20, 47, 57, 940637), verbose_name='Starting From'),
        ),
        migrations.AddField(
            model_name='streakrecord',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Starting From'),
        ),
    ]
