# Generated by Django 3.1.11 on 2021-06-22 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak_app', '0011_auto_20210622_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 18, 1, 37, 505679), verbose_name='Starting From'),
        ),
    ]
