# Generated by Django 3.1.11 on 2021-06-22 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak_app', '0012_auto_20210622_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Starting From'),
        ),
    ]
