# Generated by Django 3.1.11 on 2021-07-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak_app', '0013_auto_20210622_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='streak_image',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Streak Image'),
        ),
    ]
