# Generated by Django 3.1.11 on 2023-09-15 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak_app', '0014_streak_streak_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Starting From'),
        ),
    ]
