# Generated by Django 3.1.11 on 2021-06-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friend_server',
            new_name='server',
        ),
    ]
