# Generated by Django 3.1.11 on 2021-06-22 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0006_auto_20210620_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friendclient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friendserver', to=settings.AUTH_USER_MODEL),
        ),
    ]
