# Generated by Django 3.1.11 on 2021-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210606_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firebase_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(max_length=4, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=10, verbose_name='Mobile Number'),
        ),
    ]
