# Generated by Django 3.1.11 on 2021-06-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210615_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_image',
            new_name='profile_pic',
        ),
    ]
