# Generated by Django 3.1.11 on 2021-07-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210620_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Profile Pic'),
        ),
    ]
