# Generated by Django 3.1.11 on 2021-07-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210710_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='device_token',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Device Message Token'),
        ),
    ]
