# Generated by Django 3.1.11 on 2021-10-20 17:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userprofile_device_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, help_text='Enter a valid country code', max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Country Code', regex='^\\+[0-9]{1,4}')], verbose_name='Country Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Device ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Enter a valid 10 digit mobile number.', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Mobile Number', regex='^[1-9]\\d{9}$')], verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Profile Pic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text="The length of this field can't be longer than 100", max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Only ASCII characters allowed', regex='^[\\x00-\\x7F]*$')], verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
